# Generated by Django 3.0.2 on 2021-04-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('element_type', models.CharField(choices=[('Institution', 'Institution'), ('Node', 'Node'), ('Link', 'Link')], max_length=20)),
                ('required_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Action Type',
                'verbose_name_plural': 'Action Types',
            },
        ),
        migrations.CreateModel(
            name='MatchCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Match Criterion',
                'verbose_name_plural': 'Match Criteria',
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('element_type', models.CharField(choices=[('Institution', 'Institution'), ('Node', 'Node'), ('Link', 'Link')], max_length=20)),
                ('required_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Match Type',
                'verbose_name_plural': 'Match Types',
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Ruleset',
                'verbose_name_plural': 'Rulesets',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collation.Ruleset')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=1000)),
                ('match_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collation.MatchCriterion')),
            ],
            options={
                'verbose_name': 'Match Info',
                'verbose_name_plural': 'Match Infos',
            },
        ),
        migrations.AddField(
            model_name='matchcriterion',
            name='match_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collation.MatchType'),
        ),
        migrations.AddField(
            model_name='matchcriterion',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collation.Rule'),
        ),
        migrations.CreateModel(
            name='ActionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=1000)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collation.Action')),
            ],
            options={
                'verbose_name': 'Action Info',
                'verbose_name_plural': 'Action Infos',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collation.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collation.Rule'),
        ),
    ]
