# Generated by Django 3.0.2 on 2020-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationAllowedOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='An easy to remember name for this hostname. i.e. The organization this is for.', max_length=140, unique=True, verbose_name='name')),
                ('origin', models.CharField(max_length=255, unique=True, verbose_name='origin')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Visualization Allowed Origin',
                'verbose_name_plural': 'Visualization Map Allowed Origins',
            },
        ),
    ]
