# Generated by Django 3.2.18 on 2023-03-16 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPollImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_scheduled', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Poll+Import Event',
                'verbose_name_plural': 'Poll+Import Events',
            },
        ),
        migrations.CreateModel(
            name='PollingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='An easy to remember name for this connection. i.e. The organization this is for.', max_length=140, unique=True, verbose_name='name')),
                ('protocol', models.CharField(choices=[('https', 'HTTPS'), ('http', 'HTTP')], default='https', max_length=5, verbose_name='protocol')),
                ('hostname', models.CharField(max_length=255, verbose_name='host name')),
                ('port', models.PositiveIntegerField(default=443, verbose_name='port')),
                ('path', models.CharField(blank=True, help_text='The path to the GRENML DB node at this URL. Must end with a forward slash. (/)', max_length=255, validators=[django.core.validators.RegexValidator('(\\w+/)+')], verbose_name='path')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('token', models.CharField(blank=True, help_text='Access token provided by the peer node adminsitrator.', max_length=32, null=True)),
                ('_status_path', models.CharField(default='status', editable=False, max_length=255, verbose_name='status path')),
                ('_polling_path', models.CharField(default='grenml_export', editable=False, max_length=255, verbose_name='polling path')),
            ],
            options={
                'verbose_name': 'GRENML Polling Source',
                'verbose_name_plural': 'GRENML Polling Sources',
            },
        ),
        migrations.CreateModel(
            name='PollImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(-1, 'Aborted'), (0, 'Pending'), (1, 'Polling'), (2, 'Polled; awaiting import'), (3, 'Importing'), (4, 'Complete')], default=0)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('grenml_data', models.TextField()),
                ('poll_datetime', models.DateTimeField(blank=True, null=True)),
                ('poll_duration_seconds', models.FloatField(default=0.0)),
                ('import_datetime', models.DateTimeField(blank=True, null=True)),
                ('import_duration_seconds', models.FloatField(default=0.0)),
                ('batch_poll_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polling.batchpollimport')),
                ('polling_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polling.pollingsource')),
            ],
        ),
    ]
