# Generated by Django 3.2.18 on 2023-03-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grenml_import', '0004_importdata'),
        ('polling', '0001_initial_after_247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollimport',
            name='grenml_data',
        ),
        migrations.AddField(
            model_name='pollimport',
            name='grenml_data_import',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_import', to='grenml_import.importdata'),
        ),
    ]
