# Generated by Django 3.2.19 on 2023-06-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grenml_import', '0006_auto_20230619_1431'),
        ('polling', '0002_auto_20230322_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpollimport',
            name='duration_seconds',
            field=models.FloatField(default=0.0, verbose_name='duration seconds'),
        ),
        migrations.AlterField(
            model_name='batchpollimport',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='batchpollimport',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='batchpollimport',
            name='was_scheduled',
            field=models.BooleanField(default=False, verbose_name='was scheduled'),
        ),
        migrations.AlterField(
            model_name='pollimport',
            name='batch_poll_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polling.batchpollimport', verbose_name='batch poll import'),
        ),
        migrations.AlterField(
            model_name='pollimport',
            name='grenml_data_import',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_import', to='grenml_import.importdata', verbose_name='GRENML data import'),
        ),
        migrations.AlterField(
            model_name='pollimport',
            name='import_duration_seconds',
            field=models.FloatField(default=0.0, verbose_name='import duration seconds'),
        ),
        migrations.AlterField(
            model_name='pollimport',
            name='poll_duration_seconds',
            field=models.FloatField(default=0.0, verbose_name='poll duration seconds'),
        ),
        migrations.AlterField(
            model_name='pollimport',
            name='polling_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polling.pollingsource', verbose_name='polling source'),
        ),
        migrations.AlterField(
            model_name='pollimport',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Aborted'), (0, 'Pending'), (1, 'Polling'), (2, 'Polled; awaiting import'), (3, 'Importing'), (4, 'Complete')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pollimport',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status message'),
        ),
        migrations.AlterField(
            model_name='pollingsource',
            name='token',
            field=models.CharField(blank=True, help_text='Access token provided by the peer node adminsitrator.', max_length=32, null=True, verbose_name='Token'),
        ),
    ]
