# Generated by Django 3.2.16 on 2023-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0002_alter_basemodel_grenml_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='main',
            field=models.BooleanField(default=False, help_text='The root Topology to use for GRENML exports and distributed DB polling.  Only one Topology may be set as main.'),
        ),
    ]
