# Generated by Django 3.2.18 on 2023-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0003_topology_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='WGS84 Latitude, in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='WGS84 Longitude, in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='WGS84 Latitude, in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='WGS84 Longitude, in decimal degrees'),
        ),
    ]
