# Generated by Django 3.2.19 on 2023-06-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0004_auto_20230308_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='dirty',
            field=models.BooleanField(default=False, verbose_name='dirty'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='topologies',
            field=models.ManyToManyField(related_name='institutions', to='network_topology.Topology', verbose_name='topologies'),
        ),
        migrations.AlterField(
            model_name='link',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time and date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time and date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='topologies',
            field=models.ManyToManyField(related_name='links', to='network_topology.Topology', verbose_name='topologies'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='owners',
            field=models.ManyToManyField(related_name='elements', to='network_topology.Institution', verbose_name='owners'),
        ),
        migrations.AlterField(
            model_name='node',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time and date'),
        ),
        migrations.AlterField(
            model_name='node',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time and date'),
        ),
        migrations.AlterField(
            model_name='node',
            name='topologies',
            field=models.ManyToManyField(related_name='nodes', to='network_topology.Topology', verbose_name='topologies'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='network_topology.basemodel', verbose_name='property for'),
        ),
        migrations.AlterField(
            model_name='topology',
            name='main',
            field=models.BooleanField(default=False, help_text='The root Topology to use for GRENML exports and distributed DB polling.  Only one Topology may be set as main.', verbose_name='main'),
        ),
        migrations.AlterField(
            model_name='topology',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_topologies', to='network_topology.institution', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='topology',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='network_topology.topology', verbose_name='parent'),
        ),
    ]
