# Generated by Django 3.0.2 on 2020-07-06 13:38

from django.db import migrations, models
import django.db.models.deletion
import grenml_import.models
import network_topology.models.topology


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_topology', '0002_alter_basemodel_grenml_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=grenml_import.models.file_name)),
                ('name', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_status', models.CharField(default='pending', max_length=16)),
                ('import_message', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='importfile',
            name='source',
            field=models.CharField(choices=[('adm', 'admin import'), ('api', 'API import')], default='adm', help_text='We can import files using the admin interface or the API endpoint.', max_length=3),
        ),
        migrations.AddField(
            model_name='importfile',
            name='token_client_name',
            field=models.CharField(help_text='Equal to the client name associated to the access token in the import request. Imports done through the admin interface will use the null value.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='selected_topology',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_topology.topology'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='topology_name',
            field=models.CharField(blank=True, help_text='New name for the imported topology. Leave empty to maintain the name from the file.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='import_status',
            field=models.CharField(default='0: Import in progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='topology_name',
            field=models.CharField(blank=True, help_text='New name for the imported topology. Leave empty to maintain the name from the file. Required for Excel .xlsx files.', max_length=128, null=True),
        ),
    ]
