# Generated by Django 3.2.16 on 2022-12-14 17:13

from django.db import migrations, models
import django.db.models.deletion
import network_topology.models.topology


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0002_alter_basemodel_grenml_id'),
        ('grenml_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='selected_topology',
            field=models.ForeignKey(blank=True, default=None, help_text="The imported file's root Topology will be added as a child of the selected Topology. To add a file's contents as a top-level Topology, select the blank entry here.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_topology.topology'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='topology_name',
            field=models.CharField(blank=True, help_text='New name for the imported topology. Required for Excel .xlsx files. Not applicable for .grenml or .xml files. ', max_length=128, null=True),
        ),
    ]
