# Generated by Django 3.2.16 on 2022-12-14 17:13

from django.db import migrations, models
import django.db.models.deletion
import network_topology.models.topology


class Migration(migrations.Migration):

    dependencies = [
        ('grenml_import', '0002_auto_20221214_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importfile',
            old_name='selected_topology',
            new_name='parent_topology',
        ),
    ]
