# Generated by Django 3.2.18 on 2023-03-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_topology', '0004_auto_20230308_1431'),
        ('grenml_import', '0003_rename_parent_topology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_status', models.CharField(default='0: Import in progress', max_length=100)),
                ('import_message', models.TextField(default='')),
                ('parent_topology', models.ForeignKey(blank=True, default=None, help_text="The imported file's root Topology will be added as a child of the selected Topology. To add a file's contents as a top-level Topology, select the blank entry here.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_topology.topology')),
                ('grenml_data', models.TextField(default='')),
                ('source', models.CharField(max_length=255, null=False, blank=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
