# Generated by Django 3.2.18 on 2023-03-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grenml_import', '0004_importdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importdata',
            options={'verbose_name': 'GRENML Data Import', 'verbose_name_plural': 'GRENML Data Imports'},
        ),
        migrations.AlterModelOptions(
            name='importfile',
            options={'verbose_name': 'GRENML File Import', 'verbose_name_plural': 'GRENML File Imports'},
        ),
    ]
