# Generated by Django 3.0.14 on 2021-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published_network_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedNetworkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('file_path', models.FileField(db_index=True, upload_to='not_used')),
                ('name', models.CharField(max_length=128)),
                ('file_date', models.DateTimeField(auto_now_add=True)),
                ('grenml_export_description', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='StagedNetworkData',
        ),
    ]
