# Generated by Django 3.0.14 on 2021-11-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published_network_data', '0002_auto_20210827_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishednetworkdata',
            name='published_status',
            field=models.CharField(default='pending', max_length=16),
        ),
    ]
