# Generated by Django 3.2.13 on 2022-05-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published_network_data', '0003_publishednetworkdata_published_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednetworkdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
