# Generated by Django 3.2.13 on 2022-09-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published_network_data', '0004_alter_publishednetworkdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishednetworkdata',
            name='file_path',
        ),
        migrations.AddField(
            model_name='publishednetworkdata',
            name='file_contents',
            field=models.TextField(null=True),
        ),
    ]
