# Generated by Django 3.2.19 on 2023-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published_network_data', '0006_alter_publishednetworkdata_published_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishednetworkdata',
            options={'verbose_name': 'Published Database Snapshot', 'verbose_name_plural': 'Published Database Snapshots'},
        ),
        migrations.AlterField(
            model_name='publishednetworkdata',
            name='file_contents',
            field=models.TextField(null=True, verbose_name='file contents'),
        ),
        migrations.AlterField(
            model_name='publishednetworkdata',
            name='file_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='file date'),
        ),
        migrations.AlterField(
            model_name='publishednetworkdata',
            name='grenml_export_description',
            field=models.TextField(default='', verbose_name='GRENML export description'),
        ),
        migrations.AlterField(
            model_name='publishednetworkdata',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publishednetworkdata',
            name='published_status',
            field=models.CharField(default='pending', max_length=128, verbose_name='published status'),
        ),
        migrations.AlterField(
            model_name='publishednetworkdata',
            name='version',
            field=models.CharField(max_length=128, verbose_name='version'),
        ),
    ]
