name: run linter
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install flake8
      - run: flake8 --config django/setup.cfg
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
