# Generated by Django 3.0.2 on 2020-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False, unique=True, verbose_name='name')),
                ('display_name', models.CharField(max_length=140, verbose_name='display name')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='value')),
            ],
            options={
                'verbose_name': 'App Configuration Setting',
                'verbose_name_plural': 'App Configuration Settings',
            },
        ),
    ]
