# Generated by Django 3.0.2 on 2021-05-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='This identifies the client which will be using this token.', max_length=255, unique=True)),
                ('token', models.CharField(help_text="The access token, a random string. Use the regenerate button to populate this field in case it is empty. Send it to the peer's administrator to have this node accept the peer's requests.", max_length=32, unique=True)),
            ],
        ),
    ]
