# Generated by Django 3.2.13 on 2022-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20220815_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='description'),
        ),
    ]
