# Generated by Django 3.2.19 on 2023-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_appconfiguration_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterField(
            model_name='token',
            name='client_name',
            field=models.CharField(help_text='This identifies the client which will be using this token.', max_length=255, unique=True, verbose_name='client name'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(help_text="The access token, a random string. Use the regenerate button to populate this field in case it is empty. Send it to the peer's administrator to have this node accept the peer's requests.", max_length=32, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(blank=True, choices=[('grenml_import', 'Import'), ('grenml_export', 'Polling')], default='grenml_export', max_length=255, null=True, verbose_name='token type'),
        ),
    ]
